---
title: "string_and_factor"
author: "ww2745"
date: "2024-10-15"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)

```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"pumpkin")

str_detect(string_vec,"pumpkin")

str_detect(string_vec,"[Pp]umpkin") ##either higher or lower case letter
```


```{r}
string_vec = c(
  '7th inning stretch', ##number followed by 4 letters
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9][a-z]")
str_detect(string_vec, "^[0-9][a-zA-Z]") ##^以这个开头

```

```{r}
string_vec = c(
  'Its 7:11 in the evening', 
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") ##7sth11,. is a special character that matches anything

```

how things start to get real strange
```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") ##looking for a open bracket, special characters---put 2slashes \\
```



